name: Changelog
on:
  pull_request:
    branches:
      - main
    # Edited such that we can detect changes to the description
    types: [opened, synchronize, reopened, edited]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: check changelog
        run: scripts/check-changelog.sh . ${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ github.token }}

