name: CD
on:
  push:
    branches:
      - test-create-pr

jobs:
  nixpkgs-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: tweag/nixpkgs

      - name: Update something
        # We run bash explicitly instead of using the files shebang,
        # because the shebang is using nix-shell with dependencies we already have by default
        run: "echo foo >> README.md"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@branch-fetch-depth
        with:
          # To trigger CI for automated PRs, we use a separate machine account
          # See https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#workarounds-to-trigger-further-workflow-runs
          # and https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#push-pull-request-branches-to-a-fork
          token: ${{ secrets.MACHINE_USER_PAT }}
          push-to-fork: infinixbot/nixpkgs
          committer: infinixbot <infinixbot@infinisil.com>
          author: infinixbot <infinixbot@infinisil.com>
          branch: test-some-change
          commit-message: Some change
          title: Some change
          body: Some change
